### PR TITLE
Fix dependencies and add net46 as test target (as it was before the change)

### PR DESCRIPTION
**Pull request by alexandrnikitin**

### CODE REVIEW

**Comment by alexandrnikitin** [comment]
See https://github.com/nsubstitute/NSubstitute/blob/de7e61ba699da857a945dde8624df27efaf95133/src/NSubstitute/NSubstitute.csproj#L42-L46

**Comment by alexandrnikitin** [comment]
Maybe it's a good idea to include .NET 4.6 as a test target too to avoid such issues

**Comment by dtchepak** [comment]
Thanks for this 👍 
I don't know what the `TargetFrameworks` element does -- i thought netstandard1.3 would mean it was compatible with NET46? (based on https://github.com/dotnet/standard/blob/master/docs/versions.md)

**Comment by dtchepak** [comment]
Should `net46` also go in the `NSubstitute.csproj`? https://github.com/dtchepak/NSubstitute/blob/9f7de7f19db245ca21db87c405a845c3e1154e09/src/NSubstitute/NSubstitute.csproj#L7

**Comment by alexandrnikitin** [comment]
>  i thought netstandard1.3 would mean it was compatible with NET46? 

Yes, I also thought so. Frankly, I have no idea why it doesn't work without `System.Reflection.TypeExtensions` package. Castle.Core uses and references it, it should be there. I'm investigating that.

>Should net46 also go in the NSubstitute.csproj?

I just wanted to target .NET 4.5 explicitly and test against it. Anyway It's a good idea to have integration/smoke tests that target different frameworks like xunit has in this repo https://github.com/xunit/xunit.integration

**Pull request merged**
